# Generated by Django 5.1.4 on 2025-01-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_disciplina_escola_remove_professor_email_and_more'),
        ('core', '0003_create_groups'),
    ]

    operations = [
    ]
