# Generated by Django 5.1.4 on 2025-01-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_professor_options_alter_professor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='anos_preferidos',
            field=models.JSONField(default=list),
        ),
    ]
