# Generated by Django 5.1.4 on 2025-01-08 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_professor_anos_preferidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='escola',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='professor_atribuido',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='turmas_preferidas',
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='anos_preferidos',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='escolas_preferidas',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='pontuacao',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.AddField(
            model_name='escola',
            name='turmas_matutino',
            field=models.TextField(default=[], help_text='Lista de turmas do período matutino separadas por vírgula ou espaço.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='turmas_vespertino',
            field=models.TextField(default=[], help_text='Lista de turmas do período vespertino separadas por vírgula ou espaço.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='cargo',
            field=models.CharField(choices=[('PEB', 'Professor de Educação Básica'), ('PAEB', 'Professor de Atendimento Educacional Básico'), ('AMBOS', 'Ambos os Cargos')], default=[], help_text='Cargo do professor: PEB, PAEB ou AMBOS.', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='celular',
            field=models.CharField(default=[], help_text='Número de telefone para contato.', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='cpf',
            field=models.CharField(default=[], help_text='CPF do professor (usado como login).', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='deletado',
            field=models.BooleanField(default=False, help_text='Indica se o professor foi marcado como deletado.'),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplinas',
            field=models.CharField(default=[], help_text='Lista de disciplinas separadas por vírgula ou espaço.', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='pontuacao_paeb',
            field=models.IntegerField(blank=True, help_text='Pontuação do professor no cargo PAEB (se aplicável).', null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='pontuacao_peb',
            field=models.IntegerField(blank=True, help_text='Pontuação do professor no cargo PEB (se aplicável).', null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='retificado',
            field=models.BooleanField(default=False, help_text='Indica se os dados do professor foram retificados.'),
        ),
        migrations.AlterField(
            model_name='escola',
            name='endereco',
            field=models.CharField(help_text='Endereço da escola.', max_length=255),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(help_text='Nome da escola.', max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(help_text='Nome completo do professor.', max_length=255),
        ),
        migrations.CreateModel(
            name='Atribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(help_text='Turma atribuída (ex.: 6A, 7B).', max_length=10)),
                ('disciplina', models.CharField(help_text='Disciplina atribuída (ex.: Matemática, Português).', max_length=50)),
                ('fora_de_campo', models.BooleanField(default=False, help_text='Indica se a atribuição foi feita fora da especialidade do professor.')),
                ('escola', models.ForeignKey(help_text='Escola onde a atribuição foi feita.', on_delete=django.db.models.deletion.CASCADE, to='core.escola')),
                ('professor', models.ForeignKey(help_text='Professor atribuído.', on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
