# Generated by Django 5.1.4 on 2025-01-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_turma_disciplina_remove_turma_escola_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atribuicao',
            options={'verbose_name': 'Atribuição', 'verbose_name_plural': 'Atribuições'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterField(
            model_name='escola',
            name='turmas_matutino',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='escola',
            name='turmas_vespertino',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='EscolhaProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turmas', models.CharField(help_text='Lista de turmas escolhidas separadas por vírgula.', max_length=255)),
                ('prioridade', models.PositiveIntegerField(help_text='Prioridade atribuída à escola.')),
                ('disciplina', models.CharField(help_text='Disciplina escolhida para lecionar.', max_length=50)),
                ('periodo', models.CharField(choices=[('Matutino', 'Matutino'), ('Vespertino', 'Vespertino')], help_text='Período de interesse (Matutino ou Vespertino).', max_length=20)),
                ('data_escolha', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a escolha foi feita.')),
                ('escola', models.ForeignKey(help_text='Escola escolhida.', on_delete=django.db.models.deletion.CASCADE, to='core.escola')),
                ('professor', models.ForeignKey(help_text='Professor que fez a escolha.', on_delete=django.db.models.deletion.CASCADE, to='core.professor')),
            ],
            options={
                'verbose_name': 'Escolha do Professor',
                'verbose_name_plural': 'Escolhas dos Professores',
                'unique_together': {('professor', 'escola', 'prioridade')},
            },
        ),
    ]
