# Generated by Django 5.1.4 on 2025-01-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_atribuicao_options_alter_professor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplinas',
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina_paeb',
            field=models.CharField(blank=True, help_text='Disciplina para o cargo PAEB.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina_peb',
            field=models.CharField(blank=True, help_text='Disciplina para o cargo PEB.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='pontuacao_paeb',
            field=models.IntegerField(blank=True, help_text='Pontuação do professor no cargo PAEB.', null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='pontuacao_peb',
            field=models.IntegerField(blank=True, help_text='Pontuação do professor no cargo PEB.', null=True),
        ),
    ]
