# Generated by Django 5.1.4 on 2025-01-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_professor_disciplinas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escolhaprofessor',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='escolhaprofessor',
            name='disciplina_paeb',
            field=models.CharField(blank=True, help_text='Disciplina para o cargo PAEB', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='escolhaprofessor',
            name='disciplina_peb',
            field=models.CharField(blank=True, help_text='Disciplina para o cargo PEB', max_length=255, null=True),
        ),
    ]
