# Generated by Django 5.1.4 on 2025-01-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_escolhaprofessor_disciplina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atribuicao',
            name='gestor_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
