# Generated by Django 5.1.4 on 2025-01-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_professor_deletado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='cargo',
            field=models.CharField(choices=[('PEB', 'Professor de Educação Básica'), ('PAEB', 'Professor Adjunto de Educação Básica'), ('AMBOS', 'Ambos os Cargos')], help_text='Cargo do professor: PEB, PAEB ou AMBOS.', max_length=5),
        ),
    ]
