# Generated by Django 5.1.4 on 2025-01-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_escola_id_escola'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='status_matutino',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escola',
            name='status_vespertino',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
